### ISSUE TITLE
Add option to se stringEncoding explicitly

### ISSUE THREAD

**Issue by nektor211** [mattgwwalker/msg-extractor#100]
I've encountered issue with malformed .msg files containing bad encoding property. Therefore it would be nice to have an option to set the stringEncoding explicitly.

**Comment by athakur5** [comment]
Is there a way to get around encoding issue? I get this error for one of the files - 

`UnicodeDecodeError: 'cp950' codec can't decode byte 0x92 in position 99: illegal multibyte sequence`

**Comment by TheElementalOfCreation** [comment]
This was added in the last update. See https://github.com/mattgwwalker/msg-extractor/issues/95 for information
