### ISSUE TITLE
Msg body is being split into new line after about 72 characters

### ISSUE THREAD

**Issue by aditya2008** [mattgwwalker/msg-extractor#105]
I noticed that Msg body or recipients list it returns is being split into new line after about 72 characters. Is there any way to return the original msg?

**Comment by aditya2008** [comment]
Hi Team,
I noticed that Msg body or recipients list it returns is being split into new line after about 72 characters. Is there any way to return the original msg?  

Thanks
Aditya

**Comment by TheElementalOfCreation** [comment]
What code are you using where this happens?

**Comment by TheElementalOfCreation** [comment]
Okay, so I've figured out what you were talking about. This happens when the msg file has a defined header, and the header gets parsed by the email module. Technically, this is an issue with Python's email module, but I'll see what I can do about a fix.

**Comment by TheElementalOfDestruction** [comment]
You shouldn't have this problem with msg files anymore. Tell us if you have any more problems.
