### ISSUE TITLE
Time zone bug

### ISSUE THREAD

**Issue by patham9** [mattgwwalker/msg-extractor#106]
Should you encounter an error that has not already been reported, please do the following when reporting it:
**Bug Metadata**
* - [x] Using latest supported version of extract_msg
* Your python version: Python [3.6.4]
* How did you launch extract_msg?
  - [x] My command line or
  - [x] I used the extract_msg package 
(it happens in both)

**Describe the bug**
See the fix commit in my fork: https://github.com/patham9/msg-extractor/commit/5f7058ff6576a6303a6844a0d579b0f1af6b24bc
pytz library only works on some Linux distributions. On many smaller distributions time zone info might not be available, and even if they have it, pytz library does not correctly query it (on Corepure64 9.0), leading to the error message that time zone info is missing. I see that it is an issue in pytz, but you may also re-consider if this dependency should be referenced at all given its secondary role. In my fix I simply didn't use the library and got correct output.

[ If applicable ]
**What code did you use or can we use to reproduce this error?

```
Message("name.msg")
or
python3.6 -m extract_msg server.msg
```

Is there a message.msg file you want to share to help us reproduce this?
This bug does not depend on any specific msg file.

**Traceback**
```
 File "test.py", line 2, in <module>
    Message("/home/tc/name.msg")
 File "/home/tc/msg-extractor/extract_msg/message.py", line 87, in __init__
    self.header
  File "/home/tc/msg-extractor/extract_msg/message.py", line 219, in header
    header.add_header('Date', self.date)
  File "/home/tc/msg-extractor/extract_msg/message.py", line 272, in date
    self._date = self._prop.date
  File "/usr/local/lib/python3.6/site-packages/extract_msg/properties.py", line 123, in date
    self.__date = fromTimeStamp(msgEpoch(self.get('00390040').value)).__format__(
  File "/usr/local/lib/python3.6/site-packages/extract_msg/utils.py", line 123, in fromTimeStamp
    return datetime.datetime.fromtimestamp(stamp, tzlocal.get_localzone())
  File "/usr/local/lib/python3.6/site-packages/tzlocal/unix.py", line 131, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/local/lib/python3.6/site-packages/tzlocal/unix.py", line 125, in _get_localzone
    raise pytz.UnknownTimeZoneError('Can not find any timezone configuration')
```

**Comment by TheElementalOfCreation** [comment]
This seems more like a problem with your system. However, to try to get a proper fix, can you possibly suggest an alternative library we can use? Not having one at all leads to problems with the date-time strings.
