### ISSUE TITLE
Support UTF encoding, not just ASCII (Encoding bug)

### ISSUE THREAD

**Issue by patham9** [mattgwwalker/msg-extractor#107]
Should you encounter an error that has not already been reported, please do the following when reporting it:
**Bug Metadata**
* - [x] Using latest supported version of extract_msg
* Your python version: Python [3.6.4]
* How did you launch extract_msg?
  - [x] My command line or
  - [x] I used the extract_msg package
(it happens in both)

**Describe the bug**
See the fix commit in my fork: https://github.com/patham9/msg-extractor/commit/5f7058ff6576a6303a6844a0d579b0f1af6b24bc
By default ASCII encoding is used when open is called, now imagine the msg file contains a unicode character. What will happen? This library is deemed to crash.

[ If applicable ]
**What code did you use or can we use to reproduce this error?

```
Message("name.msg")
or
python3.6 -m extract_msg server.msg
with a file containing at least one unicode (non-ASCII) character.
```

Is there a message.msg file you want to share to help us reproduce this?
Sorry I cannot do so but I'm sure you can create a msg file with a unicode-encoded character in it yourself.

**Traceback**
```
Error with file 'name.msg': Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/extract_msg/__main__.py", line 47, in <module>
    msg.save(toJson = args.json, useFileName = args.use_filename, ContentId = args.cid)
  File "/usr/local/lib/python3.6/site-packages/extract_msg/message.py", line 616, in save
    f.write(self.body)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 75: ordinal not in range(128)
```

**Comment by TheElementalOfCreation** [comment]
Can you tell us exactly what operating system you are running?

This is definitely our fault, but I just want to know out of curiosity if your operating system is what brought this to our attention.

What was SUPPOSED to happen is that a binary file is opened and written to, but somehow this portion of the code was not updated with the rest. We'll get to working on this as soon as possible.

**Comment by TheElementalOfCreation** [comment]
This should now be fixed in the most recent versions. Please let us know if it is not. If we don't get a response within a week we will assume it is fixed and close the issue.

**Comment by lawwu** [comment]
Ran into the same issue with the latest version but wound up using `msg.save(raw=True, toJson=True)` and it worked.

**Comment by TheElementalOfCreation** [comment]
> Ran into the same issue with the latest version but wound up using `msg.save(raw=True, toJson=True)` and it worked.

To confirm, you ran into this version in 0.24.4? That is the latest version.

**Comment by TheElementalOfCreation** [comment]
@lawwu Current version is now 0.25.3. Please confirm if you are still having this issue.

If we don't get a response in the next week we will assume this issue is completely fixed and will close it.
