### ISSUE TITLE
no html body found

### ISSUE THREAD

**Issue by apenngrace** [mattgwwalker/msg-extractor#108]
In order to get your bug addressed in a timely manner, or at all :smiley:, please fill out the below bug report. Please try to make it as easy as possible for us to understand what is going on. We may close out any bugs or issues without warning that are not complete or coherent.

In the bug template below anything is [square brackets] should be filled out or removed if the item doesn't apply.

Should you encounter an error that has not already been reported, please do the following when reporting it:
**Bug Metadata**
* - [X] Using latest supported version of extract_msg
* Your python version: Python [3.7.4]
* How did you launch extract_msg?
  - [ ] My command line or
  - [X] I used the extract_msg package

**Describe the bug**

This package is not finding the html body of emails I am testing with.  This package returns None, when I would expect it to return something.  I can provide an msg file sample if you'd like.

Is there a message.msg file you want to share to help us reproduce this?
- [ ] Uploaded message (drag and drop on this window)
- [X] Emailed message as an attachment to admins: msg-extractor issue: no html body found

**Comment by TheElementalOfCreation** [comment]
If it returns None, then the msg file does not actually have one. Its really annoying, but it happens A LOT.

**Comment by TheElementalOfCreation** [comment]
Sorry, I hit the wrong button on your issue. I have not received your email, so I cannot truly confirm.

**Comment by apenngrace** [comment]
Sorry, I sent that message to Matt.  I just send the message to you as well.  There is an attachment with a sample msg file and the html file that I'm trying to extract from the msg file.

**Comment by apenngrace** [comment]
I'm going to send you another html sample, because I'm noticing that it seems to have erroneous `=` characters every 75 characters in some parts of the file.

**Comment by apenngrace** [comment]
A java open-source projected called [MsgViewer](https://sourceforge.net/projects/msgviewer/) can correctly find the html body in the sample email I gave you.  The source code can be downloaded [here](https://sourceforge.net/p/msgviewer/code/HEAD/tree/).

You just drag the msg into the box.  To see the html body, you click Information Menu > Details > HTML Code.  In Information > MSG Navigator, they also have a tree-view of the structure of the msg.

In `ViewerPanel.java` on line 319, there is a debug statement stating that the html is being extracted from RTF data.

The file `HtmlFromRtf.java` seems to be the code for stripping the RTF tags out to get the html.

In the MSG Navigator, it looks like the entry is `_substg1.0_10090102` for `RTFBodyText`, in `RTFBodyTextEntry.java` it looks like it is grabbing `UTF-16LE` data.

**Comment by TheElementalOfCreation** [comment]
That's not "finding" the "htmlbody". Htmlbody is a specific field in a msg file. What you are talking about is using a complex process to TRY to get html out of rtf, something we are still working on implementing. We are actually trying to implement a proper rtf parser to be able to generate html from even if html has not been embedded into the rtf. Also, the process of stripping away the rtf is not as simple as you might think, especially when you are trying to re-implement it from another language.

**Comment by apenngrace** [comment]
Sorry, I understand your point.  I don't know the ins and outs of the msg format.  For my purposes, stripping the rtf would work for me.  I see that I can get at `compressedRtf` using your library.  Do you have a way to decompress it?

**Comment by TheElementalOfCreation** [comment]
https://pypi.org/project/compressed_rtf/

**Comment by apenngrace** [comment]
Awesome, thanks!
