### ISSUE TITLE
How to get the sender's email?

### ISSUE THREAD

**Issue by yaronlevi** [mattgwwalker/msg-extractor#118]
Hi (-:

I hope you are feeling well these days.

I can use the following code to get the sender's name:
```
msg = extract_msg.Message(filePath)
msg.sender
```

My question is how can I get the sender's email?

Thank you for any help on the issue.

**Comment by TheElementalOfCreation** [comment]
That will give you name and email, if it is in the file. For whatever reason, outlook won't add the sender email if the person who creates the msg file is the sender.

**Comment by yaronlevi** [comment]
So is there any other way to extract the sender's emails from the .msg file?

**Comment by TheElementalOfCreation** [comment]
No

**Comment by TheElementalOfCreation** [comment]
We have checked the entire file, and if it is not in the sender property, you won't find it anywhere

**Comment by yaronlevi** [comment]
Thank You!
