### ISSUE TITLE
UnicodeDecodeError saving outlook msg

### ISSUE THREAD

**Issue by dmuijen** [mattgwwalker/msg-extractor#119]
**Bug Metadata**
* - [x] Using latest supported version of extract_msg
* Your python version: Python 3.7.3
* How did you launch extract_msg?
  - [x] I used the extract_msg package

**Describe the bug**
UnicodeDecode error when saving emails with emoji's in the message body, for example "\U0001f60a" or "\U0001F609". See attached for example MSG file.  

[ If applicable ]
**What code did you use or can we use to reproduce this error?
```
import extract_msg
msg = extract_msg.Message("hello_unicode.msg")
msg.save()
``` 

Is there a message.msg file you want to share to help us reproduce this?
- [x] Uploaded message (drag and drop on this window)

[hello_unicode.zip](https://github.com/mattgwwalker/msg-extractor/files/4504643/hello_unicode.zip)

**Traceback**
```
---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-1-255ae0c441a8> in <module>
      1 import extract_msg
      2 msg = extract_msg.Message("hello_unicode.msg")
----> 3 msg.save()

~\Anaconda3\lib\site-packages\extract_msg\message.py in save(self, toJson, useFileName, raw, ContentId, customPath, customFilename)
    614                 f.write('Date: ' + xstr(self.date) + self.__crlf)
    615                 f.write('-----------------' + self.__crlf + self.__crlf)
--> 616                 f.write(self.body)
    617 
    618             f.close()

~\Anaconda3\lib\encodings\cp1252.py in encode(self, input, final)
     17 class IncrementalEncoder(codecs.IncrementalEncoder):
     18     def encode(self, input, final=False):
---> 19         return codecs.charmap_encode(input,self.errors,encoding_table)[0]
     20 
     21 class IncrementalDecoder(codecs.IncrementalDecoder):

UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f60a' in position 14: character maps to <undefined>
```

**Additional context**
I solved it for my project by removing non-ascii chars,  changing line 616 in message.py to:
```
f.write(self.body.encode('ascii', 'ignore'))
``` 
Is there a better way to deal with this? Also, the JSON dump ensures ascii by default, would be nice if there is a fallback in place when these characters are present when saving to text

Thanks for this library, really helpful!

**Comment by TheElementalOfCreation** [comment]
The better way for us to deal with this is to probably completely rewrite the save function all together. It's one of those things that has been on the agenda for a while, but we just haven't gotten to it yet. I'll let you know when we fix the problem.

**Comment by TheElementalOfCreation** [comment]
This should be fixed in the newest version. Unfortunately I am currently unable to push the new release to pypi, so please download the newest release from here.

**Comment by TheElementalOfCreation** [comment]
Closing. If this is still a problem we will reopen it.
