### ISSUE TITLE
using as module

### ISSUE THREAD

**Issue by xsteadfastx** [mattgwwalker/msg-extractor#12]
hi. your script works perfectly for me. but i want to use it as a module. and i cant get my head around doing that. if i use something like

```python
from ExtactMsg import Message
msg = Message('foo.msg')
msg.save()
```
i get
```python
    def save(self, raw=False):
    
>       if useFileName:
E       NameError: name 'useFileName' is not defined

```
in gets defined if i run the script in a standalone way but not if i just want to use the class. even
```python
from ExtactMsg import Message
useFileName = False
msg = Message('foo.msg')
msg.save()
```
does work for me. i thought i understand something from python but i dont know how i can define that variable to use the class. maybe someone can help.

**Comment by mattgwwalker** [comment]
My sincere apologies.  That was some crap coding on my behalf.  I let slip effectively a global variable being defined in main.  Thank you for highlighting that.

I've fixed the issue. Now, your first idea executes without issue:
```
from ExtractMsg import Message
msg = Message('example-msg-files/unicode.msg')
msg.save()
```

**Comment by xsteadfastx** [comment]
ah perfect :) thank you. everything works perfectly. your module saves me alot of trouble...
