### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'html'

### ISSUE THREAD

**Issue by joanrodriguezr** [mattgwwalker/msg-extractor#132]
**Bug Metadata**
* extract-msg-0.25.0
* Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
* How did you launch extract_msg?
  - From command line at the directory where the .msg file is.

**Describe the bug**
I have just installed your library with:
pip install git+https://github.com/mattgwwalker/msg-extractor

And  going to the directory where the .msg is I have executed the following comand from a Powershell as per your project documentation:
 python -m extract_msg .\MensajeAbrebien.msg

The file "MensajeAbrebien.msg" is a .msg file that can be opened double clicking on it and it show information in my Outlook client.

**What code did you use or can we use to reproduce this error?

```
PS C:\temp> python -m extract_msg .\MensajeAbrebien.msg
Error with file '.\MensajeAbrebien.msg': Traceback (most recent call last):
  File "C:\Python37pro\lib\site-packages\extract_msg\__main__.py", line 47, in <module>
    msg.save(toJson = args.json, useFileName = args.use_filename, ContentId = args.cid, html = args.html, rtf = args.html)
AttributeError: 'Namespace' object has no attribute 'html'
```

Is there a message.msg file you want to share to help us reproduce this?

Due to my company policies I can't upload that file here, I will only upload screenshots shadowing company info

**Traceback**

**Screenshots**
The .msg file opened in Outlook client:
![image](https://user-images.githubusercontent.com/14201057/86220082-5aff1d80-bb83-11ea-82a5-2f73de07363e.png)

**Additional context**
As I say the .msg file opens OK with an Outlook client, but trying to automate and extract the attachments and the email body I can't progress using your library. Any help would be appreciated. Thanks in advance!

**Comment by TheElementalOfCreation** [comment]
Yeah, that's our bad. Some future code was left in a state that WILL work, just not right now. It will be fixed in the next version.

**Comment by TheElementalOfCreation** [comment]
This should now be fixed. Please let us know if you encounter any more problems in the future.

**Comment by joanrodriguezr** [comment]
I have tested the v0.25.1 and it works fine now. Your quick response is very appreciated. Thank you!!!
