### ISSUE TITLE
Accessing headerDict throws AttributeError

### ISSUE THREAD

**Issue by opsdisk** [mattgwwalker/msg-extractor#134]
In order to get your bug addressed in a timely manner, or at all :smiley:, please fill out the below bug report. Please try to make it as easy as possible for us to understand what is going on. We may close out any bugs or issues without warning that are not complete or coherent.

In the bug template below anything is [square brackets] should be filled out or removed if the item doesn't apply.

Should you encounter an error that has not already been reported, please do the following when reporting it:
**Bug Metadata**
* - [x] Using latest supported version of extract_msg **version 0.25.1**
* Your python version: **Python 3.7.5**
* How did you launch extract_msg?
  - [ ] My command line or
  - [x] I used the extract_msg package

**Describe the bug**
When trying to reference a message's `headerDict` attribute, an AttributeError is raised.

[ If applicable ]
**What code did you use or can we use to reproduce this error?

```python
import extract_msg
m = extract_msg.openMsg("test.msg")
m.headerDict
```

Is there a message.msg file you want to share to help us reproduce this? **No**
- [ ] Uploaded message (drag and drop on this window)
- [ ] Emailed message as an attachment to admins: [Enter Subject Line Here]

**Traceback**
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/msg-extractor/extract_msg/message.py in headerDict(self)
    385         try:
--> 386             return self._headerDict
    387         except AttributeError:

AttributeError: 'Message' object has no attribute '_headerDict'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-4-a0e9f0865b1d> in <module>
      1 import extract_msg
      2 m = extract_msg.openMsg("test.msg")
----> 3 m.headerDict

/tmp/msg-extractor/extract_msg/message.py in headerDict(self)
    386             return self._headerDict
    387         except AttributeError:
--> 388             self._headerDict = dict(self.header._header)
    389             self._headerDict.pop('Received')
    390             return self._headerDict

AttributeError: 'Message' object has no attribute '_header'
```

**Screenshots**

![image](https://user-images.githubusercontent.com/8660252/87256808-6132ab00-c45b-11ea-93f2-37192cd7a4cd.png)

**Additional context**

In `msg-extractor/extract_msg/message.py`, changing line 388 from:

```python
self._headerDict = dict(self.header._header)
```

to

```python
self._headerDict = dict(self.header._headers)
```

worked for me:

```bash
git clone https://github.com/mattgwwalker/msg-extractor.git
cd msg-extractor

egrep header._header extract_msg/message.py
sed -i "s/header._header/header._headers/" extract_msg/message.py
egrep header._header extract_msg/message.py

python setup.py install
```

**Comment by TheElementalOfCreation** [comment]
Firstly, please use our bug report template. Thank you.

Secondly, the reason "Received is removed is because it is a useless property when you try to get it from the dict. Multiple entries in the header use it and so it overwrites itself.

**Comment by opsdisk** [comment]
My bad.  Here's the PR: https://github.com/mattgwwalker/msg-extractor/pull/135

**Comment by TheElementalOfCreation** [comment]
We need you to COMPLETELY fill out the form or your issue will be closed. Thank you.

**Comment by opsdisk** [comment]
What specifically in the form is missing?  Do I need to update the `CHANGELOG.md` as well?

**Comment by TheElementalOfCreation** [comment]
@opsdisk That's not how this works. When you create an issue that is a bug report, we require that you use our template. Failure to do so will cause your issue to be closed. If you attempt to open a new issue, you can then copy the form and put your issue information into it. Please go edit your initial post and make it conform to our template. Thank you.

**Comment by opsdisk** [comment]
Updated original issue with the bug report info.  I'd created the original issue using the "Reference in new issue" option and it didn't auto-populate with the bug report questionnaire.

![image](https://user-images.githubusercontent.com/8660252/87257013-04d08b00-c45d-11ea-8e07-df6d7090ce3e.png)

**Comment by TheElementalOfCreation** [comment]
You shouldn't have any more issues using `Message.headerDict` now

**Comment by opsdisk** [comment]
Looks good!  Thanks for the quick turnaround and maintaining the library.
