### ISSUE TITLE
name 'UnrecognizedMSGTypeError' is not defined

### ISSUE THREAD

**Issue by joanrodriguezr** [mattgwwalker/msg-extractor#138]
**Bug Metadata**
* Version of extract_msg: [0.25.1]
* Your python version: Python [v3.7.0:1bf9cc5093]
* How did you launch extract_msg?
  -  I used the extract_msg package from a .py file

**Describe the bug**
We are using your library because we need to extract information from a .msg file which is arriving our systems within a .zip file in out Outlook mailbox.
In the process we extract the .msg to a local path and before calling your library we check the file exists, in some cases we get the following exception when calling your library: 

name 'UnrecognizedMSGTypeError' is not defined

If you need me to modify some setting from your library to provide more verbose logs I can reproduce the error again, please let me know. Thanks in advance

**What code did you use or can we use to reproduce this error?

```
 if os.path.isfile(msgPath):
	msg = None
	try:
		import extract_msg
		msg = extract_msg.openMsg(msgFilePath)
	except Exception as msgEx:
		Logger.error('{}Could not get msg object from msgFilePath. Exception was: {}'.format(strSpaces,msgEx))
		return
```
Is there a message.msg file you want to share to help us reproduce this?
- I need to speak to the Company Policy group  but unfortunately by default the don't allow us to share information out of our company, so I can't add here the .msg file.

**Traceback**
```
2020-07-31 19:31:42,880 ERROR    Could not get msg object from msgFilePath. Exception was: name 'UnrecognizedMSGTypeError' is not defined
```

**Screenshots**
None

**Additional context**
None

**Comment by TheElementalOfCreation** [comment]
I'll likely get a patch out within the next half hour. However, I think that error likely means that your program is actually running into the line that was supposed to raise that exception, and you will likely be coming right back after the patch with a new error.

**Comment by TheElementalOfCreation** [comment]
I've put out a patch that should have fixed this issue. Please rerun your code to confirm the specific error is not happening. If you get a different error while rerunning the code you may post it here instead of opening a new thread.

**Comment by joanrodriguezr** [comment]
Thank you for the quick answer, I will try with v0.25.3 and will let you know as soon as I can.

**Comment by joanrodriguezr** [comment]
Hi, I tried to install through "pip install extract-msg==0.25.3"

But I got the following error:

ERROR: Could not find a version that satisfies the requirement extract-msg==0.25.3 (from versions: 0.20.6, 0.20.7, 0.20.8, 0.21.0, 0.22.0, 0.22.1, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.24.4)
ERROR: No matching distribution found for extract-msg==0.25.3
WARNING: You are using pip version 20.1.1; however, version 20.2 is available.
You should consider upgrading via the 'c:\python37pro\python.exe -m pip install --upgrade pip' command.

I don't know if there's a time to wait for the 0.25.3 version to be available to be installed with pip, or am I doing something wrong?

**Comment by TheElementalOfCreation** [comment]
@joanrodriguezr Unfortunately I have not personally been able to upload the newest distributions to PyPi right now due to some strange errors I am getting. The moment I try to compress the files into a distribution, something seems to be corrupting the README.rst making it so that it suddenly refused to upload. I've been working for the last few versions on trying to solve this. For now, you should be able to download the module from git and run `pip install .` from the folder that contains setup.py. Otherwise, you can also use `pip install git+https://github.com/mattgwwalker/msg-extractor/` to install the most recent version

**Comment by joanrodriguezr** [comment]
Ok, thank you! Meanwhile I have modified the file that has the import missing that was provoking the error, adding that import line manually. 

I will use the second option you propose to install the most recent version.

Thanks again, If i can't reproduce the error with this version I will let you know, so you can close this issue

**Comment by TheElementalOfCreation** [comment]
Apparently there was just a minor error in the setup.py. Now that I have fixed that I have been able to successfully upload new distributions to pypi. You should now be able to install 0.25.3 directly from pypi.

**Comment by joanrodriguezr** [comment]
I have tested it, and from my side this issue can be closed as FIXED. Thanks again for the quick response and support @TheElementalOfCreation
