### ISSUE TITLE
Question: Outlook for OSX

### ISSUE THREAD

**Issue by elewis33** [mattgwwalker/msg-extractor#14]
Can this be used with Outlook for Mac formatted messages? Those files appear to have an extension of ".olk15Message" rather than ".msg". I could certainly just try it out, or read through the code, but thought I'd ask anyway.

**Comment by mattgwwalker** [comment]
I'm sorry, I haven't any idea.  However, should you have an example Mac version that you'd be happy to share, I'd be very pleased to add it to the collection-of-msg-files-that-should-really-become-tests.

Cheers,

Matthew

**Comment by TheElementalOfCreation** [comment]
Please try it out and tell us the results. If it doesn't work, please provide a traceback along with your python version.
