### ISSUE TITLE
"NameError : name 'filename' not found" when setting useFileName=True

### ISSUE THREAD

**Issue by Pierm91** [mattgwwalker/msg-extractor#17]
Hello,

It seems that when setting the parameter useFileName=True in the Message.save function, it returns a NameError : "filename is not defined".
After checking in the ExtractMsg.py code, I don't see where the filename attribute is defined for the Message class. Am I the only one to get this error ?

I am using an Anaconda with python 3.5.
Best regards

**Comment by TheElementalOfCreation** [comment]
Can you be a bit more specific as to the error? Which line is specifically giving that error?

**Comment by TheElementalOfCreation** [comment]
Fixed in most recent update. If you believe the issue still exists, please re-open this thread.
