### ISSUE TITLE
Handle .msg files having .eml files as attachment

### ISSUE THREAD

**Issue by KshitizAgrawal** [mattgwwalker/msg-extractor#18]
How to handle the case when stream tag 37010102 is missing from the attachment storage. There is a storage with a tag 3701000D present in the attachment storage which again contains an attachment of .eml extension.
Can we save the attachment of the .msg file in which stream tag 37010102 is missing but tag 3701000D is present or having .msg or .eml as attachment.

**Comment by mattgwwalker** [comment]
Can you provide an example file where this has occurred?  If you can do that, and you're happy that we add it to the list of examples in the repository, that would help me test any changes.

**Comment by KshitizAgrawal** [comment]
Thanks @mattgwwalker for a quick resposne and giving interest for the issue.
Please find attached the zip file containing a msg file. The msg contains an eml file as attachement.
[other.msg.zip](https://github.com/mattgwwalker/msg-extractor/files/1541634/other.msg.zip)

**Comment by TheElementalOfCreation** [comment]
This should be resolved in the most recent version (v0.24.3). Please contact us if this is not.
