### ISSUE TITLE
Provide a PYPI package

### ISSUE THREAD

**Issue by giampaolo** [mattgwwalker/msg-extractor#23]
Currently the designated way to install msg-extractor is via GIT. There is no tarball on PYPI. This has different drawbacks:

- It is slow to download compared to a plain HTTP fetch from the official PYPI repo
- It is error prone when it comes to pin a specific revision/cset in requirements.txt (e.g. `git+https://github.com/mattgwwalker/msg-extractor.git@2a24c9950d34932ed5979693cb70d758d78715df#egg=ExtractMsg`). It took me a while to understand I couldn't `import ExtractMsg` because I had to append `#egg=ExtractMsg` in requirements.txt.
- a GIT url cannot be used as a `install_requires=...` dependency in setup.py so you have to necessarily use pip + requirements.txt.
- relying on requirements.txt means that if package A depends from msg-extractor and packages B and C depend from package A you'll have to put msg-extractor in all 3 requirements.txt of pkg A, B and C (whereas with setup.py you would only set it in setup.py of A). This is currently the major annoyance for us.

If this is desirable I can provide a PR to ease up this process (e.g. via Makefile + [.pypirc](https://docs.python.org/2/distutils/packageindex.html#pypirc)).

EDIT - here's a PR which paves the way to PYPI upload + unit tests: https://github.com/mattgwwalker/msg-extractor/pull/26

**Comment by giampaolo** [comment]
Superseeded by #25.

**Comment by giampaolo** [comment]
Would you be open to a PR which turn this lib into a :

- provides a setup.py, sets package name to `msgextractor`
- move MsgExtractor.py to msgextractor.py for PEP8 compliance
- API usage would be:
```
from msgextractor import Message
m = Message(...)
```
- cmdline usage would be
```
python -m msgextractor example.msg
```

**Comment by giampaolo** [comment]
I submitted a PR here: https://github.com/mattgwwalker/msg-extractor/pull/26

**Comment by frennkie** [comment]
I was considering using this in a project until I noticed that there is no PyPI package for this... @giampaolo mentioned all the reasons why it's advisable to have release versions on PyPI. Please consider this.

**Comment by TheElementalOfCreation** [comment]
There is now a PyPi package.
