### ISSUE TITLE
Unable to retrieve the date from header

### ISSUE THREAD

**Issue by sanjay12590** [mattgwwalker/msg-extractor#30]
Hi Guys,

Can anyone please help me get the date from header .Unable this field for the email.

Thanks
Sanjay

**Comment by TheElementalOfCreation** [comment]
Please provide more information. Do you know that the msg file actually contains a header? If you have 7zip, open the msg file and look for a file named "__substg1.0_007D001F". if it does not have that file, the msg file is missing its header. At this point in time, the program cannot get the date without that header file.

**Comment by TheElementalOfCreation** [comment]
Notice, updated version in my latest pull request can retrieve the date without that file. 

Unfortunately, I have found a file that it has issues with about this, but that file is literally 1 in 1000

**Comment by TheElementalOfCreation** [comment]
Fixed in most recent update. If you believe the issue still exists, please re-open this thread.
