### ISSUE TITLE
How to get msg.HTMLbody rather than msg.body?

### ISSUE THREAD

**Issue by Morriaty-The-Murderer** [mattgwwalker/msg-extractor#32]
Hi,
I have got a .msg file containing tables, and Message.body would transform all the table cells split by `\r\n`

| First Header  | Second Header |
| ------------- | ------------- |
| Content Cell  | Content Cell  |

```python
print(msg.body)
First Header 
Second Header
Content Cell
Content Cell
```

So I'd like to know how to get HTMLbody or some other style tags?

**Comment by elewis33** [comment]
Use BeautifulSoup on the body HTML. 

Earl

**Comment by Morriaty-The-Murderer** [comment]
Hi @elewis33 , thank you for your reply. 

But there is no html tags in raw Message.body, I suppose BeautifulSoup would not help.

The extracted body is like this
```
HeaderA\r\n\r\nHeaderB\r\n\r\nValueA\r\n\r\nValueB
```

So I cannot tell where to spilt into rows or columns.

**Comment by TheElementalOfCreation** [comment]
According to the documentation for msg files, if an msg file has an html body included it will be in the stream `__substg1.0_10130102` but not all msg files have this. 

Most of them do, however, have a compressed rtf stream that can be decompressed (found in `__substg1.0_10090102` ). The decompressed rtf stream then has encapsulated html tags which can be extracted using a de-encapsulator. Unfortunately, I have not been able to find one for python (one that works at least). I am currently working on a pure python version, but it is not fun and will definitely take a while. 

I have a pull request active that I am still updating and the message class already has a property for the compressed rtf stream. I'm going to be adding in the HTMLbody property soon.

**Comment by TheElementalOfCreation** [comment]
Correction, the compressed rtf body does not ALWAYS have encapsulated html, unfortunately. So sometimes it is possible to get an MSG file that simply doesn't have html in it.

**Comment by torfsen** [comment]
Perhaps you could try to use the RTF directly. There seem to be several RTF-libraries for Python, although I haven't tested any of them.

**Comment by TheElementalOfCreation** [comment]
About that... none of them actually work properly. Rtf is a real pain to parse through (trust me, I know) and I REQUIRE html for my purpouses. So any library that doesnt actually work properly in all situations just won't cut it.

I'm currently working in my own, and it's really not very fun.

**Comment by TheElementalOfCreation** [comment]
I mean, they work for well formatted rtf, but if it is NOT well formatted, like A LOT of the rtf that comes out of msg files that I've seen.

**Comment by torfsen** [comment]
@TheElementalOfCreation Perhaps you could call a command line RTF-to-HTML converter from within your script. There seem to be several (more than Python converter modules), and some of them may be able to deal with the malformatted RTF from msg files.

**Comment by Sicos1977** [comment]
I don't know if Phyton can call .NET assemblies but if so then you could try to use my MSGReader. It can de-encapsulate HTML from RTF... and believe me that was a pain in the ass to build.

You can find the library overhere --> https://github.com/Sicos1977/MSGReader

**Comment by TheElementalOfCreation** [comment]
@Sicos1977 Unfortunately I don't know anything about .NET assemblies, so I wouldn't be able to tell you. I'm already using https://github.com/mazira/rtf-stream-parser which is a JavaScript library. I may eventually do a rather direct conversion into pure python. Honestly, for the sake of more widespread compatibility with different flavors of python (like PyPy), the closer to pure python, the better. The JavaScript library works quite well. I will try to check out your program though.

**Comment by Sicos1977** [comment]
My library has an almost full blown RTF parses that also support high and low surrogate pairs. It is has a class Reader that you can use the just pull in an MSG file and have it extract everything in it to a folder. It handles all the reading over the most used MSG file properties like; from, to, subject, attachments, etc...

**Comment by Sicos1977** [comment]
It's also build to always produce an HTML file when needed, it does the following things:

- Check if there is an HTML body
- If not then check if there is HTML encapsulated into RTF
- If not then get the text body and convert that to HTML
- If not then just produce an empty HTML file

I don't know what you are building but it looks like you are doing something similar then the requirements I had when building MSGReader

**Comment by TheElementalOfCreation** [comment]
Fixed in most recent update.

**Comment by dochakovsky** [comment]
Could you please provide some more details about how it was fixed? Message.htmlBody is always null, information about the table is not available in Message.body. If you have a chance to provide some usage example how to extract a table from MSG (or how to convert MSG to HTML) that would be great. Thank you!

**Comment by TheElementalOfCreation** [comment]
@dochakovsky the latest updates contain a direct reference to the html body. However, as stated earlier (did you read the entire thread?) some msg files don't have this. In that case, your best bet is to hope that the compressed rtf body has encapsulated html, and use something like https://github.com/mazira/rtf-stream-parser on the decompressed rtf to access it.

You can use https://github.com/delimitry/compressed_rtf for the compressed rtf.

**Comment by dochakovsky** [comment]
@TheElementalOfCreation the table information (rows, columns) should be somewhere inside MSG, the table displayed correctly when I'am opening this MSG file with Outlook. Honestly I have no idea in what form the table information is saved but I assume it can be saved in HTML form (maybe I am wrong). I am trying to look at the Message.htmlBody and it is NULL. Most likely, as you are saying the HTML (and table) information should be inside the compressed rtf body in this case? I will try to use what you are suggesting to parse it. If you have some idea/information how to properly extract tables from MSG files please let me know (maybe looking for HTML is not the best choice). Thank you for your quick response!

**Comment by TheElementalOfCreation** [comment]
@dochakovsky that information is in the rtf body. Whether it is in pure rtf or encapsulated html will determine how easy it will be for you to use.

**Comment by dochakovsky** [comment]
I see. Thank you @TheElementalOfCreation
