### ISSUE TITLE
Extract .msg wrapped in .msg files

### ISSUE THREAD

**Issue by sanjayb678** [mattgwwalker/msg-extractor#39]
Hi,
I need some help in extracting .msg files attached to .msg file. I have these outlook messages wrapped in .msg and need to extract the subject, body and date from the same. Can you please help with the same. 

Thanks in advance.

**Comment by TheElementalOfCreation** [comment]
Hello sanjayb678.

In regards to your question, an embedded Message class instance can be retrieved from the attachments like so:
```
MessageInstance.attachments[x].msg
```
Where `MessageInstance` is an instance of the message class, and `x` is the attachment number. The retrieved Message class instance works exactly the same as the top-level message instance.

Here is a full example:

```
>>>> import ExtractMsg
>>>> ms = ExtractMsg.Message("path/to/msg/file.msg")
>>>> ms
<ExtractMsg.Message instance at 0x02d8a5f8>
>>>> ms.attachments[0]
<ExtractMsg.Attachment instance at 0x0367d1c0>
>>>> ms.attachments[0].msg
<ExtractMsg.Message instance at 0x02d8a5f8>
>>>> ms.attachments[0].msg.body
'This is an example of the body text'
```

Hope this helps.

**Comment by TheElementalOfCreation** [comment]
WAIT SORRY THAT WAS A MISTAKE
Sorry, but the code I posted will refer you back to the original msg file. Sorry. I'll update it in a minute

**Comment by TheElementalOfCreation** [comment]
Okay, I fixed the code to properly work this time. Make sure you have the latest version of the ExtractMsg script before using it
