### ISSUE TITLE
read message by ExtractMsg.py

### ISSUE THREAD

**Issue by NadaFEKI** [mattgwwalker/msg-extractor#41]
I have this error KeyError: '00390040' when I try to read a msg file without date attribut. 
I didn't have this kind of problem 4 days ago

**Comment by TheElementalOfCreation** [comment]
Ah, I've noticed this happening a few times. If you can, please send a copy of problematic files to arceusthe@gmail.com. Ensure that they are in an archive file like zip, rar, 7z, etc. before sending them. I'm still trying to figure out why this is happening, but the error there is with retrieving the date from the properties file. I suspect that it might be being stored under a slightly different key in some instances.

**Comment by TheElementalOfCreation** [comment]
Pushed temporary patch to fix. Leaving open as this is not properly fixed

**Comment by TheElementalOfCreation** [comment]
Sorry, I made an error in the last version. Use version 0.13

**Comment by TheElementalOfCreation** [comment]
Wow, I keep making little mistakes. Give me a few minutes and I should have a fully working patch, one that doesn't have errors. It will be version 0.14

**Comment by NadaFEKI** [comment]
Thank you
 
----- Original message -----From: Ken Peterson <notifications@github.com>To: mattgwwalker/msg-extractor <msg-extractor@noreply.github.com>Cc: NadaFEKI <nada.feki2@fr.ibm.com>, Author <author@noreply.github.com>Subject: Re: [mattgwwalker/msg-extractor] read message by ExtractMsg.py (#41)Date: Wed, Oct 31, 2018 5:16 PM 
Pushed temporary patch to fix. Leaving open as this is not properly fixed

**Comment by NadaFEKI** [comment]
OK no problem, let me know when it's ready
good luck
 
----- Original message -----From: Ken Peterson <notifications@github.com>To: mattgwwalker/msg-extractor <msg-extractor@noreply.github.com>Cc: NadaFEKI <nada.feki2@fr.ibm.com>, Author <author@noreply.github.com>Subject: Re: [mattgwwalker/msg-extractor] read message by ExtractMsg.py (#41)Date: Wed, Oct 31, 2018 5:33 PM 
Wow, I keep making little mistakes. Give me a few minutes and I should have a fully working patch, one that doesn't have errors. It will be version 0.14

**Comment by TheElementalOfCreation** [comment]
Fixed
