### ISSUE TITLE
Message constructor no longer supports StringIO datastream

### ISSUE THREAD

**Issue by NL66278** [mattgwwalker/msg-extractor#44]
According to the README the Message constructor should support a datastream. In 0.3 it did actually support this. In 0.17 no longer for StringIO. The culprit is in line 567 where the len of the path argument (the first argument, that could) is checked. Of course a StringIO object has no __len__ attribute, so this fails.
```
  File "/home/odorboprd11/odoo/parts/runbot/runbot/static/build/05694-10-0-import-development-dc9dd7/parts/odoo/odoo/addons/mail_drop_target/models/mail_thread.py", line 26, in message_process_msg
    message_msg = Message(StringIO(b64decode(message)))
  File "/home/odorboprd11/odoo/parts/runbot/runbot/static/build/05694-10-0-import-development-dc9dd7/eggs/ExtractMsg-0.17-py2.7.egg/ExtractMsg.py", line 657, in __init__
    elif len(path) < 1536:
AttributeError: StringIO instance has no attribute '__len__'
```

Maybe test wether path argument actually has a len()/__len__ attribute, or just put it in a try/except block.

**Comment by TheElementalOfCreation** [comment]
I don't even know why you would use a StringIO instance instead of a string or bytes, but whatever. I'll fix it in version 0.18

**Comment by TheElementalOfCreation** [comment]
However, you did bring my attention back to some of the code I wrote when I was half asleep. Even though I'm not fully awake right now, I realize that I need to make the testing system for paths and stuff much more comprehensive. For version 0.18, I'll just put in a test for stringio, but 0.19 will have a very comprehensive test code to ensure problems like this won't happen again.

Seriously though, why StringIO?

**Comment by NL66278** [comment]
Actually the use of StringIO was implemented by a very smart collegue of mine, so I will ask him. In the meantime I will test what happens when I just pass the message as a string.

**Comment by NL66278** [comment]
I asked. StringIO was used because README.md asked for either filename or datastream. Now tested with just passing a string and this works perfectly.

**Comment by TheElementalOfCreation** [comment]
HOnestly, I'm surprised it ever worked. I created subclasses of StringIO and BytesIO that have __len__ and StringIO ALWAYS failed to be recognized as an olefile

**Comment by NL66278** [comment]
Anyway the temporary fix looks good to me.

**Comment by TheElementalOfCreation** [comment]
This issue should be resolved. If it is not, please comment and I will reopen it.
