### ISSUE TITLE
Extract Certain information from Header

### ISSUE THREAD

**Issue by AdwCrossed** [mattgwwalker/msg-extractor#45]
When retrieving the header via self.header it produces a huge chunk of string that consist of:
Content-Type
Content-Transfer-Encoding
Date
From:
To:
....
and more.

My question is does this plugin support extraction of only certain information such as(example):
IPAddress of sender/receiver
Return-Path

Appreciate the help!

**Comment by AdwCrossed** [comment]
Alright I'll try to do further research on this.
Thanks for the reply and time!

**Comment by AdwCrossed** [comment]
> Yes and no.
> Do we support it at all? Yes, but you must know the code for the data stream.
> 
> Do we support it easily though a direct property, no.
> 
> As it is not something that would commonly be asked for, it is not a high priority, so it may be a while before it is implemented.

Could you enlighten me on where the code for data streams are located at! Appreciate it!

**Comment by TheElementalOfCreation** [comment]
`ExtractMsg.Message._getStream` and `ExtractMsg.Message._getStringStream`

**Comment by TheElementalOfCreation** [comment]
Right now the current priority is on bug fixes, then on documentation on how to actually use the program. Those should help immensely in the future.

**Comment by AdwCrossed** [comment]
> `ExtractMsg.Message._getStream` and `ExtractMsg.Message._getStringStream`

Thanks alot!!



> Right now the current priority is on bug fixes, then on documentation on how to actually use the program. Those should help immensely in the future.

Yes, understandable!

**Comment by AdwCrossed** [comment]
__

**Comment by TheElementalOfCreation** [comment]
Notice, should the header exist in the message file, you can retrieve it with `message_instance.header` which is a property of the `Message` class. From there, you can manually look through the data to see if the information you want is included.
