### ISSUE TITLE
py3 tests failing

### ISSUE THREAD

**Issue by punkrokk** [mattgwwalker/msg-extractor#47]
So - in [this line](https://github.com/mattgwwalker/msg-extractor/blob/52dc4100924b7a8d980f6ea0a3d31d7e7b6a251c/ExtractMsg.py#L754)

the iteritems() function is used which is deprecated in python3. I discovered this when trying to use the tests in python3. 

My question is, does py3 invocation not hit this code? And the tests do? Or is this a bug?

**Comment by TheElementalOfCreation** [comment]
To put it simply, I have no idea why the tests even call that line. It's just there so that the class is more like a dict, and therefore is easier for other people to implement into whatever they are making. It is never actually called during normal operation.
