### ISSUE TITLE
pypi module naming

### ISSUE THREAD

**Issue by punkrokk** [mattgwwalker/msg-extractor#50]
Currently the setup.py calls this package ExtractMsg.

Based on the [package naming convention in PEP0008](https://www.python.org/dev/peps/pep-0008/#package-and-module-names), I want to suggest the name is either changed to msg_extractor or extract_msg.

If you all agree, which do you prefer?

**Comment by mattgwwalker** [comment]
Seems to me that extract_msg is the smallest change.

Thanks for helping us with this.

**Comment by punkrokk** [comment]
Hey - so in thinking about this - since the repo is called msg-extractor, I'd recommend the pip package, and actually the ExtractMsg.py file be reorganized in the following directory / naming structure:

repo root
.
folder: msg_extractor
                 msg_extractor.py
                 __init__.py
                 __version__.py

we would update our __init__.py import statement as follows:

from msg_extractor.msg_extractor import Attachment, Message, Prop, Properties, Recipient

See this PR for my thought. I'd need to do a bit more testing before I'd just release it. I'm pretty sure this would not break anything, but need to check.

**Comment by TheElementalOfCreation** [comment]
While I am not against the renaming, changing the structure of how the program itself works is a different matter. The problematic thing is that many pieces DIRECTLY rely on each other, making it so that importing one part of the module would cause every single other part to be imported. As such, I don't see the benefit in reorganizing the structure.

**Comment by TheElementalOfCreation** [comment]
Also, I too would prefer "extract_msg"

**Comment by punkrokk** [comment]
Here's how I would look at what I'm suggesting - I'm not REALLY changing the structure - I'm moving into into a subfolder, which is where PEP8 says it belongs, and if you are going to do the stuff you say in the readme - it will be much easier to expand in that folder anyway.

It's useful to point out that from an end user perspective - nothing will change because of the __init__.py handles that for them with this updated import: 

from msg_extractor.msg_extractor import Attachment, Message, Prop, Properties, Recipient

`from msg_extractor.msg_extractor`
or
`from extract_msg.extract_msg`

I don't **really** care if it's extract_msg, I just wonder why the repo is called msg-extractor? I'm being picky, but it's slightly confusing to me. I don't have any skin in this so whatever you guys think makes the most sense.

**Comment by TheElementalOfCreation** [comment]
> Here's how I would look at what I'm suggesting - I'm not REALLY changing the structure - I'm moving into into a subfolder, which is where PEP8 says it belongs, and if you are going to do the stuff you say in the readme - it will be much easier to expand in that folder anyway.

Fair enough. Unfortunately, I have unpublished code that I need to finish and then push. After that, I will stop working so we can sort all this out so that we don't have to pretty much retry everything because of some code changes.

> It's useful to point out that from an end user perspective - nothing will change because of the **init**.py handles that for them with this updated import:
> 
> ```
> from extract_msg.extract_msg import Attachment, Message, Prop, Properties, Recipient
> ```

Why not just do something like this:
```
from extract_msg.extract_msg import *
```

> I don't **really** care if it's extract_msg, I just wonder why the repo is called msg-extractor? I'm being picky, but it's slightly confusing to me. I don't have any skin in this so whatever you guys think makes the most sense.

\*shrugs\* I didn't name it, so I can't really comment.

**Comment by TheElementalOfCreation** [comment]
Given the amount of things to be imported, would it be best to import them using one line or two?

**Comment by punkrokk** [comment]
For __init__.py, one line is probably fine. Are the functions that are outside of classes needed to be imported? 

Smells funny to me….


Cheers, 

JP

**Comment by TheElementalOfCreation** [comment]
> For __init__.py, one line is probably fine. Are the functions that are outside of classes needed to be imported? Smells funny to me…. Cheers, JP

Some functions are used in more than one class, and the functions are not based on and specific class.

Most of the imports had to do with constants, but I fixed that now. Again, I'll get back to you when I am done reworking the entire thing.

Also, what about the ```if __name__ == '__main__'``` code?

**Comment by punkrokk** [comment]
So, I’m my opinion we could break the shared functions out into a “utils.py” file and import them into each class. I’d actually break each class into its own file, and maybe define your constants ( for now) in init.py. More on that later.

Happy to do a call on Friday or next week to share some ideas. 

Cheers,

JP

**Comment by punkrokk** [comment]
the if __name__ == '__main__' code only gets executed if we instantiate the class from the command line. In my case I import the class, so I do my own setup, that fits my needs. 

Said differently, in this case, the __main__ enable the option to run from the cli, while keeping the ability to import the class. 


Cheers,

JP

**Comment by TheElementalOfCreation** [comment]
Right now the biggest problem is that I can't figure out what I did wrong. I try to install the module in its current state but this happens:

```
C:\Users\Creation>pypy -m pip install --upgrade git+https://github.com/mattgwwalker/msg-extractor
Collecting git+https://github.com/mattgwwalker/msg-extractor
  Cloning https://github.com/mattgwwalker/msg-extractor to c:\users\creation\appdata\local\temp\pip-req-build-s6av7d
Requirement already satisfied, skipping upgrade: olefile in c:\users\creation\desktop\pypy2-v5.9.0-win32\site-packages (from extract-msg==0.20.1) (0.46)
Requirement already satisfied, skipping upgrade: imapclient in c:\users\creation\desktop\pypy2-v5.9.0-win32\site-packages (from extract-msg==0.20.1) (2.1.0)
Requirement already satisfied, skipping upgrade: six in c:\users\creation\desktop\pypy2-v5.9.0-win32\site-packages (from imapclient->extract-msg==0.20.1) (1.11.0)
Building wheels for collected packages: extract-msg
  Running setup.py bdist_wheel for extract-msg ... error
  Complete output from command C:\Users\Creation\Desktop\pypy2-v5.9.0-win32\pypy.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\creation\\appdata\\local\\temp\\pip-req-build-s6av7d\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\users\creation\appdata\local\temp\pip-wheel-rcl6o1 --python-tag pp260:
  running bdist_wheel
  running build
  running build_py
  file extract_msg.py (for module extract_msg) not found
  file extract_msg.py (for module extract_msg) not found
  running build_scripts
  creating build
  creating build\scripts-2.7
  error: file 'c:\users\creation\appdata\local\temp\pip-req-build-s6av7d\extract_msg.py' does not exist

  ----------------------------------------
  Failed building wheel for extract-msg
  Running setup.py clean for extract-msg
Failed to build extract-msg
Installing collected packages: extract-msg
  Running setup.py install for extract-msg ... error
    Complete output from command C:\Users\Creation\Desktop\pypy2-v5.9.0-win32\pypy.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\creation\\appdata\\local\\temp\\pip-req-build-s6av7d\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\creation\appdata\local\temp\pip-record-l3mjlx\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    file extract_msg.py (for module extract_msg) not found
    file extract_msg.py (for module extract_msg) not found
    running build_scripts
    creating build
    creating build\scripts-2.7
    error: file 'c:\users\creation\appdata\local\temp\pip-req-build-s6av7d\extract_msg.py' does not exist

    ----------------------------------------
Command "C:\Users\Creation\Desktop\pypy2-v5.9.0-win32\pypy.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\creation\\appdata\\local\\temp\\pip-req-build-s6av7d\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\creation\appdata\local\temp\pip-record-l3mjlx\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\creation\appdata\local\temp\pip-req-build-s6av7d\
```

Take a look when you can and tell me if you know what I did wrong

**Comment by punkrokk** [comment]
Are you in my latest commit in my PR? Try that

**Comment by punkrokk** [comment]
You could also create a next-release branch and merge my PR there so you can get the changes easier

**Comment by punkrokk** [comment]
#49

**Comment by TheElementalOfCreation** [comment]
"Branch has confilicts" "These conflicts are too complex to be resolved in the web editor"

**Comment by TheElementalOfCreation** [comment]
I made several commits after that pull request

**Comment by punkrokk** [comment]
ok. Why don't we scrap this PR and LMK when you are ready for me to take your changes and move them over. I think we are working against each other here. 

If you have made commits but don't push them I can't help too much. 

I just pushed an update that should solve your build problem.

But I then get an iteritems issue (this is a py2<-> py3 compatibility issue)

```
import extract_msg
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/punkrokk/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/182.4505.26/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/punkrokk/repos/msg-extractor27/extract_msg/__init__.py", line 1, in <module>
    from extract_msg.extract_msg import Attachment, Properties, Props, Recipient, Message, msg_epoch, fromdatetime, constants, parse_type, properHex
  File "/Users/punkrokk/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/182.4505.26/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/punkrokk/repos/msg-extractor27/extract_msg/extract_msg.py", line 710, in <module>
    class Properties:
  File "/Users/punkrokk/repos/msg-extractor27/extract_msg/extract_msg.py", line 820, in Properties
    iteritems.__doc__ = dict.iteritems.__doc__
AttributeError: type object 'dict' has no attribute 'iteritems'
```

**Comment by TheElementalOfCreation** [comment]
Okay, I did a dumb and have now fixed it. Please confirm that the new version install properly on python 3

**Comment by punkrokk** [comment]
Ok . So, you are pushing updates directly to master? 

Cheers,

JP

**Comment by punkrokk** [comment]
Is there a way we can chat? Like gchat or something? 

Cheers,

JP

**Comment by TheElementalOfCreation** [comment]
smh, I nearly forgot to move the main code.

Discord? is gchat google chat?

**Comment by punkrokk** [comment]
I don’t have discord. Gchat is what is now called google hangouts. 

Cheers,

JP

**Comment by TheElementalOfCreation** [comment]
> I don’t have discord. Gchat is what is now called google hangouts. Cheers, JP
> […](#)
> On Nov 22, 2018, at 10:30 PM, Ken Peterson ***@***.***> wrote: smh, I nearly forgot to move the main code. Discord? is gchat google chat? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

perfect. You can add me at arceusthe@gmail.com

**Comment by punkrokk** [comment]
Got it. Messaged you there?

Cheers,

JP

**Comment by punkrokk** [comment]
@TheElementalOfCreation This is resolved.
