### ISSUE TITLE
Still Python3.4 support is broken in version 0.20

### ISSUE THREAD

**Issue by cs-satish-mishra** [mattgwwalker/msg-extractor#51]
class Properties:
  File "/opt/cyops-integrations/.env/lib/python3.4/site-packages/ExtractMsg.py", line 798, in Properties
    iteritems.__doc__     = dict.iteritems.__doc__
AttributeError: type object 'dict' has no attribute 'iteritems'

**Comment by TheElementalOfCreation** [comment]
Will be fixed in version 0.20.2

**Comment by cs-satish-mishra** [comment]
> Will be fixed in version 0.20.2

Thank You ! @TheElementalOfCreation

**Comment by TheElementalOfCreation** [comment]
Okay, most things should be fixed right now. Debugging is not properly supported though. Not easily, anyways. You have to do `extract_msg.base.debug = True`

**Comment by TheElementalOfCreation** [comment]
Version 0.21.0 is out. If your issue is fixed, please close this.
