### ISSUE TITLE
Error when body is Null

### ISSUE THREAD

**Issue by NicolleLouis** [mattgwwalker/msg-extractor#62]
Should you encounter an error that has not already been reported, please do the following when reporting it:
* - [x] Using latest supported version of extract_msg
* Your python version: Python 3.5.2
* How did you launch extract_msg?
  - [ ] My command line or
  - [x] I used the extract_msg package

**Describe the bug**
I tried to extract a file without body, i got an error 'expected string or bytes-like object for Message._body'

**What code did you use or can we use to reproduce this error?**

```
import extract_msg


mail = extract_msg.Message(file_to_extract)
print(mail)
```

Is there a message.msg file you want to share to help us reproduce this?
- [ ] Uploaded message (drag and drop on this window)
- [ ] Emailed message as an attachment to admins: [Enter Subject Line Here]

**Screenshots**
![image](https://user-images.githubusercontent.com/30229476/49740270-228faa00-fc94-11e8-9ac7-7253ef6fbb8a.png)

**Additional context**
I have a PR to solve this issue (cf above screenshot) but I have no right to push on your repo.

I forced to self._body to string type on line 392 of message.py. It solves the issue

**Comment by TheElementalOfCreation** [comment]
I'm closing your pull because the code we are working with is leaps and bounds ahead of the current public release and it would just be easier to fix it manually than try to merge conflicting pulls. Also, we are going to be using an if statement that will confirm that body is at least a string before running any of the re code.

I'll tell you when the release that should fix this is posted.

**Comment by TheElementalOfCreation** [comment]
By the way, can you please confirm that the type that is causing the issue is body being None and not something else?

**Comment by NicolleLouis** [comment]
Thanks a lot for your reactivity. 

Yes, that's the precise issue

**Comment by TheElementalOfCreation** [comment]
Version 0.21.0 is out. If your issue is fixed, please close this.

**Comment by NicolleLouis** [comment]
Perfect, I'm closing it
