### ISSUE TITLE
readpst output support

### ISSUE THREAD

**Issue by akshatdewan** [mattgwwalker/msg-extractor#71]
Hi, 

I tried extracting text from .msg files generated from readpst (https://linux.die.net/man/1/readpst) but it ends up in errors. 
I ran the following command on my pst export 
```
readpst -o ./msgs -D -r -te -S -m abc.pst
```
And when I run extract_msg on the .msg files  generated in the previous step, I get the following error
```
$ python extract_msg/  -i xyz.msg -p . -u
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/data/chatbot/scripts_2/msg-extractor/extract_msg/__main__.py", line 21, in <module>
    msg = Message(filename)
  File "extract_msg/message.py", line 82, in __init__
    self.recipients
  File "extract_msg/message.py", line 462, in recipients
    self._recipients.append(Recipient(recipientDir.split('#')[-1], self))
  File "extract_msg/recipient.py", line 17, in __init__
    self.__email = msg._getStringStream(self.__dir + '/__substg1.0_39FE').encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'
```
Does anyone know how to resolve this issue? 

Best,
Akshat

**Comment by TheElementalOfCreation** [comment]
Greetings. Sorry for the late reply, but can you please confirm you are using the latest version (0.22.0)?

**Comment by akshatdewan** [comment]
Hi, thanks! I was indeed not using the latest version. Updating to the version - 0.22.0 seemed to have resolved the issue. Thanks!

**Comment by akshatdewan** [comment]
Hi, 
I followed your advice and upgraded to the latest version (0.22.0) but I am now encountering the following behavior:

When I run extract_msg on readpst generated .msg files, it fails while it continues to work fine for regular .msg files copied manually from MS Outlook client app. 

Would you happen to know if there is a fix for it? I have tried all different combinations of cmd line arguments for readpst. 
```
(msg-extractor) $ python extract_msg/  --out . --use-filename abc.msg
Error with file 'abc.msg': Traceback (most recent call last):
  File "/anaconda3/envs/msg-extractor/lib/python3.5/site-packages/extract_msg-0.22.0-py3.5.egg/extract_msg/message.py", line 220, in header
    return self._header
AttributeError: 'Message' object has no attribute '_header'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "extract_msg/__main__.py", line 44, in <module>
    with Message(x[0]) as msg:
  File "/anaconda3/envs/msg-extractor/lib/python3.5/site-packages/extract_msg-0.22.0-py3.5.egg/extract_msg/message.py", line 85, in __init__
    self.header
  File "/anaconda3/envs/msg-extractor/lib/python3.5/site-packages/extract_msg-0.22.0-py3.5.egg/extract_msg/message.py", line 224, in header
    self._header = EmailParser().parsestr(headerText)
  File "anaconda3/envs/msg-extractor/lib/python3.5/email/parser.py", line 68, in parsestr
    return self.parse(StringIO(text), headersonly=headersonly)
TypeError: initial_value must be str or None, not bytes

```

**Comment by TheElementalOfCreation** [comment]
So, as far as I can tell without looking at it in depth, it seems like it might actually be a problem with readpst. The only other possibility I can think of is that the header is being encoded in something other than unicode-16-le. However, testing that is easy. Simply run the following, replacing `{file path}` with the path of the file:
```
import olefile
a = olefile.OleFileIO({file path})
print('Unicode version found: {}'.format(a.exists('__substg1.0_007D001F')))
print('Other version found: {}'.format(a.exists('__substg1.0_007D001E')))
```

Once you have done that, please respond with the results.

**Comment by akshatdewan** [comment]
Many thanks for your answer. 

Here is what I obtained:

```
Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 21:41:56)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import olefile
>>> a = olefile.OleFileIO('abc.msg')
>>> print('Unicode version found: {}'.format(a.exists('__substg1.0_007D001F')))
Unicode version found: False
>>> print('Other version found: {}'.format(a.exists('__substg1.0_007D001E')))
Other version found: True
>>>

```

**Comment by TheElementalOfCreation** [comment]
Okay, your answer confirms that it is a bug in our software. However, it also seems to confirm that there is a bug in THEIR software as well (or at least a missing feature) if you are not able to enforce the usage of unicode-16-le. We will look into it.

To help with the process, would you be able to provide a few sample msg files for us to use and possibly include in testing? We would seriously rather not have to educate ourselves on the usage of a new (to us) program to be able to generate these test files. It is perfectly fine if you do not feel comfortable with doing this for us.

**Comment by akshatdewan** [comment]
Hey, I would definitely like to help you. I cannot share the already available msg files because of their confidential nature but if you could tell what kind of metadata is held in msg files, I would try to create some fake emails, export, extract using readpst and share the resulting msgs with you.

**Comment by TheElementalOfCreation** [comment]
The problem is that we currently do not have any files encoded in a format that is not unicode-16-le. Your msg files are being created in such a way. If you can generate a fake email at all it should be perfect for analysis.

**Comment by akshatdewan** [comment]
I will try to get the approval from my superior. I will keep you posted.

**Comment by akshatdewan** [comment]
Here is an example email. 
[test_msg_file.zip](https://github.com/mattgwwalker/msg-extractor/files/2881213/test_msg_file.zip)

**Comment by TheElementalOfCreation** [comment]
The main thread for this issue is now #75 and is nearly fixed
