### ISSUE TITLE
How to extract attachments? 

### ISSUE THREAD

**Issue by qq0r** [mattgwwalker/msg-extractor#72]
In order to get your bug addressed in a timely manner, or at all :smiley:, please fill out the below bug report. Please try to make it as easy as possible for us to understand what is going on. We may close out any bugs or issues without warning that are not complete or coherent.

In the bug template below anything is [square brackets] should be filled out or removed if the item doesn't apply.

Should you encounter an error that has not already been reported, please do the following when reporting it:
**Bug Metadata**
* - [x] Using latest supported version of extract_msg
* Your python version: Python [2.7 | 3.6.7]
* How did you launch extract_msg?
  - [ ] My command line or
  - [x] I used the extract_msg package

**Describe the bug**

[ If applicable ]
**What code did you use or can we use to reproduce this error?

```
[put your code here]
```

Is there a message.msg file you want to share to help us reproduce this?
- [ ] Uploaded message (drag and drop on this window)
- [ ] Emailed message as an attachment to admins: [Enter Subject Line Here]

**Traceback**
```
[Put your traceback here]
```

**Screenshots**
[Insert any screenshots or debug pictures here]

**Additional context**
[Add any other context about the problem here.]

**Comment by qq0r** [comment]
My code: 
import glob, os
import extract_msg

msg = extract_msg.Message("unicode.msg")
body = msg._getStringStream('__substg1.0_1000')
sender = msg._getStringStream('__substg1.0_0C1F')
attachments = ???

**Comment by TheElementalOfCreation** [comment]
Why on earth are you trying to do it all manually? 

```
body = msg.body
sender = msg.sender
attachments = msg.attachments
```

Dp youself a favor and use the constructs we made. We made them for a reason. Attachments are a structure rather than a single stream, so trying to do them manually is not fun. Plus, doing them manually in unnecessary.

**Comment by qq0r** [comment]
Initially I used your constructs but thought that wasn't the way to do it, because it gives me some references/ids to the attachments - not the actual attachment text. How can I get from the ids to the actual text?

In: attachments = msg.attachments
In: attachments
Out: [<extract_msg.attachment.Attachment at 0x2299764ebe0>,
 <extract_msg.attachment.Attachment at 0x2299765f160>]

I appreciate your answers, and I am sorry about my (probably) stupid questions, but I am a novice at this.

**Comment by TheElementalOfCreation** [comment]
Unfortunately, we have yet to properly get around to updating the readme and making a proper usage guide, so the knowledge is not as common. Now, while at first it seems like just a reference to an attachment, that is a table of attachment objects. Simply use `msg.attachments[num].data`

**Comment by qq0r** [comment]
Alright. Thanks a lot for taking your time to answer and explain the usage of the construct. It is much appreciated.
