### ISSUE TITLE
--raw does not appear to be an option

### ISSUE THREAD

**Issue by crattis** [mattgwwalker/msg-extractor#73]
Should you encounter an error that has not already been reported, please do the following when reporting it:
**Bug Metadata**
* Using extract_msg-0.22.0
* Your python version: Python 3.6.4
* How did you launch extract_msg?
  -  My command line: python3 -m extract_msg
  

**Describe the bug**
the --raw option as listed in the read me does not appear to be a valid option.

 python3 -m extract_msg --raw Aw_Rech_M69G10L.msg
usage: extract_msg [-h] [--use-content-id] [--dev] [--validate] [--json]
                   [--file-logging] [--verbose] [--log LOG]
                   [--config CONFIG_PATH] [--out OUT_PATH] [--use-filename]
                   msg [msg ...]
extract_msg: error: unrecognized arguments: --raw

and:

 python3 -m extract_msg -h
usage: extract_msg [-h] [--use-content-id] [--dev] [--validate] [--json]
                   [--file-logging] [--verbose] [--log LOG]
                   [--config CONFIG_PATH] [--out OUT_PATH] [--use-filename]
                   msg [msg ...]

extract_msg: Extracts emails and attachments saved in Microsoft Outlook's .msg
files. https://github.com/mattgwwalker/msg-extractor

positional arguments:
  msg                   An msg file to be parsed

optional arguments:
  -h, --help            show this help message and exit
  --use-content-id, --cid
                        Save attachments by their Content ID, if they have
                        one. Useful when working with the HTML body.
  --dev                 Changes to use developer mode. Automatically enables
                        the --verbose flag. Takes precedence over the
                        --validate flag.
  --validate            Turns on file validation mode. Turns off regular file
                        output.
  --json                Changes to write output files as json.
  --file-logging        Enables file logging.
  --verbose             Turns on console logging. Implies --verbose
  --log LOG             Set the path to write the file log to.
  --config CONFIG_PATH  Set the path to load the logging config from.
  --out OUT_PATH        Set the folder to use for the program output.
                        (Default: Current directory)
  --use-filename        Sets whether the name of each output is based on the
                        msg filename.

**Comment by TheElementalOfCreation** [comment]
The readme needs to be updated a bit. The `--raw` option has been removed.
