### ISSUE TITLE
Cannot extract metadata for "SOME" .msg files(especially from the sent box)

### ISSUE THREAD

**Issue by ameyn21** [mattgwwalker/msg-extractor#89]
**Bug Metadata**
* - [ ] Using latest supported version of extract_msg
* Your python version: Python [3.6.7]
* How did you launch extract_msg?
  - [ ] I used the extract_msg package

**bug**
I am not able to fetch the sender's email addresses for SOME emails. Only the name of the sender gets extracted. Mostly these emails are from the sent box.
I have emailed the .msg file for issue reproduction to mattgwwalker@gmail.com and arceusthe@gmail.com. 

```
import extract_msg

filepath = r'C:\Users\Amey\SAR\emails not working\testing extract_msg.msg'

with extract_msg.Message(filepath) as msg:
    msg_sender = msg.sender
    msg_to = msg.to        
    print(msg_sender, msg_to)
```

Is there a message.msg file you want to share to help us reproduce this?
- [ ] mailed to owners (subject: testing extract_msg)

**Screenshots**
[Insert any screenshots or debug pictures here]
![image](https://user-images.githubusercontent.com/8626077/59341591-ca5e6100-8d25-11e9-91ec-02c470027d59.png)

**Comment by TheElementalOfCreation** [comment]
This is not a bug. This is a limitation of the msg format. Sometimes, usually when the sender of the email is the one who creates the msg file, the email just doesn't get put ANYWHERE in the file.

**Comment by TheElementalOfCreation** [comment]
And even if it IS in the file, the location is inconsistent and impossible to determine automatically.
