### ISSUE TITLE
building on windows for python 3.5+

### ISSUE THREAD

**Issue by agcopenhaver** [mattgwwalker/msg-extractor#92]
I'm getting the following issue when building on windows for python 3.6

cloned the repo, and ran `python setup.py install`, which yielded the following error:

![image](https://user-images.githubusercontent.com/15128391/61002415-7ef0a000-a32f-11e9-8463-f6aa66c08b09.png)

It appears to be related to issues with a character in the readme, which is read in the setup.py file. Because encoding isn't set, I believe it's defaulting to system default cp1252, which is causing the issue.

I added a few lines to the setup.py script to deal with this and it built fine:
<pre><code># read in the description from README
if os.name=='nt' and sys.version_info[0] >= 3:
    with open("README.rst", encoding='utf-8') as stream:
        long_description = stream.read()
else:
    with open("README.rst") as stream:
        long_description = stream.read()
</code></pre>

**Comment by TheElementalOfCreation** [comment]
If it is using cp1252, as far as I am aware an encoding issue of a single abuse should be _impossible_ so this surprises me. To my knowledge, cp1252 is an extension of iso-8859-1, an encoding I often use with strings because it will accept any byte value without errors.

Let me take a look to see if I can find out what's happening.

**Comment by TheElementalOfCreation** [comment]
Wait, you say "3.5+" but our support is actually for "3.6+". Perhaps that is causing an issue?

**Comment by agcopenhaver** [comment]
I actually got this problem on both 3.6 and 3.7 as well

**Comment by TheElementalOfCreation** [comment]
We are looking into this. Can you tell me if this happens if you try to pip install?
```python -m pip install extract-msg```

**Comment by TheElementalOfCreation** [comment]
This has been replicated. Fix will be pushed soon.
