### ISSUE TITLE
Is the offset for In-Reply-To, References headers known?

### ISSUE THREAD

**Issue by pudo** [mattgwwalker/msg-extractor#96]
We would love to be able to reconstruct email message threads from .msg files. While this brilliant parser already has support for the `Message-ID` header, I haven't seen reference to the `In-Reply-To` and `References` headers, which form its counterpart. This would be necesary in order to re-construct full message chains.

**Comment by TheElementalOfCreation** [comment]
Header reconstruction for files missing one is still a work in progress. It requires that we try to pull all or that information from other places in the file which may not exist, and it is a lot of information.
