### ISSUE TITLE
How can I retrieve the attachment type / extension in real-time?

### ISSUE THREAD

**Issue by JuneSunshine** [mattgwwalker/msg-extractor#99]
How can I retrieve the attachment type / extension in real-time?
I've tried to use attachment.type, but it only returns 'data' which is not what I expected. 
Is there a way to do so instead of saving the attachments then read their extension names?

**Comment by ParitoshSingh07** [comment]
If your goal is to get the extension from filenames, you can do that in memory without issues.
Something like the following snippet can help:
```
for att in mail_object.attachments:
    Filename = att.longFilename if att.longFilename else att.shortFilename
    name, ext = os.path.splitext(Filename)
    print(ext)
```

**Comment by stevesimmons** [comment]
> What about the attachment size? Is there a way to retrieve that as well?

`num_bytes = len(att.data)`

**Comment by TheElementalOfCreation** [comment]
> > What about the attachment size? Is there a way to retrieve that as well?
> 
> `num_bytes = len(att.data)`

It should be noted that this will only work if att.data is the actual data of the attachment. For example, if the attachment is an embedded msg file, I believe this code will actually raise an exception.

**Comment by TheElementalOfCreation** [comment]
I believe this issue should now be closed. If you do not agree, please reply as to your reasoning within one week. If we do not get a response in that time, this issue will be closed.
